name: "Build Python Package"
description: "Use script to build python package of SimpleITK"
inputs:
  python-version:
    description: "Python version to build"
    required: true
    default: "3.8"
  continue-on-error:
    description: "Continue on error"
    required: false
    default: false
  VCVAR_OPTIONS:
    description: "Visual Studio vcvarsall.bat options"
    required: false
    default: amd64 -vcvars_ver=14.2
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      id: cpy
      with:
        python-version: ${{ inputs.python-version }}
    - name: Build Pyhon ${{ steps.cpy.outputs.python-version }}
      continue-on-error: ${{ inputs.continue-on-error }}
      shell: bash
      if: runner.os == 'macOS'
      run: |
        ${CTEST_SOURCE_DIRECTORY}/.github/workflows/scripts/mac_build_python.sh
    - name: Build Pyhon ${{ steps.cpy.outputs.python-version }}
      continue-on-error: ${{ inputs.continue-on-error }}
      shell: cmd
      if: runner.os == 'Windows'
      run: |
        call  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"  ${{ inputs.VCVAR_OPTIONS }}
        bash ${{ env.CTEST_SOURCE_DIRECTORY }}/.github/workflows/scripts/win_build_python.sh
