# These pipelines are executed on every PR, and merge. They should provide quick
# coverage for the common wrapped language and the SimpleITK core and examples.

trigger:
  - master
  - next
  - release
  - archive_test
variables:
  ExternalDataVersion: 1.2.0
jobs:
  - job: Linux
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: |
          echo "${BUILD_ARTIFACTSTAGINGDIRECTORY}"
          echo "This is a test archive" | gzip -c > ${BUILD_ARTIFACTSTAGINGDIRECTORY}/archive.zip
        displayName: 'Creating archive'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)/
          artifactName: Java
        continueOnError: true
